### ISSUE TITLE
soul fire aspect/fire aspect not exclusive with Ensorcellation

### ISSUE THREAD

**Issue by arzadu** [Crystal-Nest/soul-fire-d#14]
**Describe the bug**
soul fire aspect and fire aspect can be put on the same weapon. 

**To Reproduce**
get anvil, put soul fire and fire aspect onto the same weapon, no issues. it's also happened to me via regular enchanting.

**Expected behavior**
nothing breaks, but it doesn't make a whole lot of sense? soul fire overwrites fire aspect, so it does more damage, but it doesn't make sense why it could happen.

**Screenshots**
![2023-01-07_19 50 14](https://user-images.githubusercontent.com/97483584/211175744-3059553e-bf23-48ff-8a00-c084a9a63dbd.png)

**System information:**
 - Minecraft version: 1.18.2
 - Mod version: 2.0.0.1

**Additional context**
along with this, exclusivity with Ensorcellation's frost aspect would be nice!

**Comment by arzadu** [comment]
please ignore the tooltip on the sword, it's for my modpack and is irrelevant for this bug report

**Comment by Crystal-Spider** [comment]
This is weird, it should indeed be exclusive with normal Fire Aspect (and maybe also Frost Aspect, depending on how Frost Aspect is coded).  
I will look into this

**Comment by arzadu** [comment]
It's possible that it's a mod compat issue with either apotheosis or ensorcellation, as I am running both mods. I'll check with just soul fire'd in a bit

**Comment by Crystal-Spider** [comment]
Yeah that would be great. If the issue doesn't persist when only Soul Fire'd is installed, please check also with Soul Fire'd + Apotheosis and Soul Fire'd + Ensorcellation.  
If my guess is any good, Apotheosis shouldn't be the problem. I would like to check the source code for Ensorcellation too, but it's not open source. My guess is, by exclusion, that Ensorcellation is the problem.  
If you can confirm whether it's just Soul Fire'd or which other mod is causing the issue I will try my best to solve it.

**Comment by arzadu** [comment]
as it happens, it's an issue with Ensorcellation and Soul Fire'd. I did also check to see if it was an issue with their custom fire aspect, but disabling it in their server config did not fix the issue. Hopefully this helps, and thanks so much!

**Comment by Crystal-Spider** [comment]
Thank you for the infos!  
Currently I'm working on a big improvement of the Soul Fire'd API along with new configuration options to enable/disable Soul Fire enchantments.  
As soon as I'm done with all of that, I will start working on this issue.

Anyway, I'm puzzled as of why this is happening. My best guess is that Ensorcellation is completely overriding the Fire Aspect enchantment (and probably that configuration option just makes it behave either like Vanilla or not) and thus my compatibility check, that simply checks against Vanilla Fire Aspect, fails.  
However I cannot know for sure until I do some in-depth testing, since that mod is not open source 🥲

In the meantime, thank you again for the infos and the bug report!

**Comment by Crystal-Spider** [comment]
I confirmed my guess was right and I found the way to fix it. Now I just have to complete my other tasks before releasing v3.0.0.0 with the fix.

**Comment by Crystal-Spider** [comment]
Version 3.0.0.0 is now out and it includes the fix for this issue.  
While I was doing some testing I found out another "incompatibility" bug between this mod and Ensorcellation: Soul Flame enchantment does not work.  
On my end there's nothing I can do about it, but I have already reached out to the team behind Ensorcellation and asked if they can add compatibility on their end, providing also a snippet of code that should fix the problem. I hope they will accept my suggestion.
