### ISSUE TITLE
Soul_Flame bow enchantment issue

### ISSUE THREAD

**Issue by NathanCPlaster** [Crystal-Nest/soul-fire-d#16]
Hello, I am on Forge 43.2.4 for 1.19.2.  Mod version soulfired- 1.19.2-3.0.0.0.
I believe there is an issue with the bow enchantment or I am misunderstanding its use.
I am playing with mods however there are no compatibility issues.
When a bow has the soul_flame enchantment on it, the arrow burns red and does not seem to benefit from being fired through soul fire.  Mobs hit also do not burn blue but instead ignite as if hit with normal flame.  
Arrows fired from an unenchanted bow through soul fire take on the blue hue and deal additional damage.  Mobs hit with these arrows burn blue.
Mobs or the player that walk into soul fire burn blue and take additional damage.
The sword enchantment soul_flame_aspect works perfectly with no issues.

**Comment by Crystal-Spider** [comment]
Do you maybe have Ensorcellation installed?

**Comment by NathanCPlaster** [comment]
I do not have Ensorcellation installed, however I do have cofh_core which is a required dependency for Ensorcellation.  I have cofh_core for some of the other mods in the list.

**Comment by Crystal-Spider** [comment]
That's the problem. Unfortunately it overrides how fire enchantment is applied to arrows, which nullifies my code for setting them on the proper kind of fire. If you look at #14 it's a bug I discovered a while ago and asked the COFH team to fix it, but they said they won't do it anytime soon (basically they will only if this mod becomes big enough so that changing their code is worth it). Despite how much I'd like to fix this, there's nothing much I can do about this, I'm very sorry.

**Comment by NathanCPlaster** [comment]
I removed cofh_core and the mod that required it because yours is worth more.  Thank you for your help!

**Comment by Crystal-Spider** [comment]
Aww thank you!
