### ISSUE TITLE
Minor irks about enchants

### ISSUE THREAD

**Issue by anoomolu** [Crystal-Nest/soul-fire-d#25]
**Describe the bug**
1 -Soul Fire Aspect doesn't spawn in Bastions, while Soul Flame does.

2 -Soul Flame and Soul Fire Aspect aren't marked as Treasure enchants (like Mending, Frost Walker etc.). I appreciate that they show up in the enchanting table, but considering they're pretty strong and are supposed to be found in Bastions (mid to late game structures), I feel like they're better suited to be treasure-only by default.

**To Reproduce**
Steps to reproduce the behavior (1):
1. Go to bastion_other_loot_modifier.json in data.

**Expected behavior**
I'd expect to find entries for both Soul Flame and Soul Fire Aspect. Only the former has one. 

**Screenshots**
Adding the below enables both to spawn, albeit very rarely imo.
![image](https://github.com/Nyphet/soul-fire-d/assets/77850233/93047098-b75c-4cf2-80f4-b48900536afd)

**System information:**
 - Minecraft version: 1.16.5 Forge
 - Mod version: 3.1.0.0

**Additional context**
Not really context but more a thank you for making this mod, I love the attention to detail and compatibility this has with other mods ^^

**Comment by Crystal-Spider** [comment]
Thank you for your kind words and the support! Let me reply in order:
1. It's intentional, Soul Fire Aspect can spawn on swords found in chests, you cannot find the book. That's also why it's not present in this mod datapack, Minecraft Vanilla already enchants randomly the swords based on all registered suitable enchantments.
2. Some versions ago they were by default tresure enchantments, but I changed it after another request. To be honest if it was for me all enchantments would be available in the enchanting table, but regardless of my personal taste what I can do is add new configuration options that let tweak the soul enchantments more than it's currently possible, so that each player can have the customization they prefer. It will come along with version 3.2.0.0 and [data driven fires](#4) (a feature I'm working on to let people register fires of other mod without needing to make a mod themselves, just a datapack)

Thank you again!

**Comment by Crystal-Spider** [comment]
Version 3.2.0.0 is now out, along with the new configuration options!
