### ISSUE TITLE
Firework rockets broken on servers

### ISSUE THREAD

**Issue by Kn0tzer** [Crystal-Nest/soul-fire-d#30]
**Describe the bug**
On servers using firework rockets while flying doesn't boost you forward

**To Reproduce**
1. Join a server
2. Fly with an elytra
3. Use a firework rocket

**Expected behavior**
For the firework to boost you forward in the air

**System information:**
 - Minecraft version: 1.20.1
 - Mod version:  Fabric 1.20.1 v3.2.0.0

**Comment by Crystal-Spider** [comment]
Is the mod installed on the server too?

**Comment by Kn0tzer** [comment]
> Is the mod installed on the server too?

No

**Comment by Crystal-Spider** [comment]
Then this is not a bug. It's the fifth time someone opens an issue about this. Please, check if similar issues already exist before opening a new one and please make sure to check the mod page.    
This mod is required on **both** server **and** client, otherwise it can't work properly.  
This is clearly and explicitly written on the mod page:  
![Opera Snapshot_2023-09-25_010313_github com](https://github.com/Nyphet/soul-fire-d/assets/65339023/9a840b56-6769-45b1-aaf0-d7f95401abdd)
