### ISSUE TITLE
Data Driven Fire (Datapacks)

### ISSUE THREAD

**Issue by Fiopon** [Crystal-Nest/soul-fire-d#4]
Allow modpack creators to add support for modded fire from other mods by using a datapack & resourcepack combo

**Comment by Crystal-Spider** [comment]
I don't believe this would be an important addition since making an addon-mod to support other mods' fires is as easy as creating a blank mod and following the Wiki from [Setup](https://github.com/Nyphet/soul-fire-d/wiki/Setup) to [Registering your Fire](https://github.com/Nyphet/soul-fire-d/wiki/Registering-your-Fire).  
Once a fire is registered and all required assets are loaded, this mod handles everything else from adding enchantments, to setting on the correct kind of fire when a zombie hits another entity, etc.  
The Fire registered can be of another mod, it shouldn't matter at all.

What I will do is making this more explicit on the wiki, but let me know here if you need help: I'll be glad to help.

**Comment by Crystal-Spider** [comment]
Wiki has been updated with the following new section: [Registering another mod's fire](https://github.com/Nyphet/soul-fire-d/wiki/Registering-your-Fire#registering-another-mods-fire).

**Comment by Crystal-Spider** [comment]
I changed my mind and I will allow data driven fires to be a thing in a future version (4.0.0.0).  
Note however that, even if a data driven fire is registered, the resource pack files regarding it will be loaded only if used in a json model of an actually existing block or item. For example only using a datapack and resource pack to create a fire won't work well because, despite the fact that everything else will work fine, the sprites won't be loaded. So data driven fires can only be used to register fires of other mods without requiring to make a mod of your own.

**Comment by Crystal-Spider** [comment]
Code developing done, just need to port the feature on all active versions and write the wiki page.

**Comment by Crystal-Spider** [comment]
With version 3.2.0.0 the feature is already available, the wiki page will come soon too.

**Comment by Crystal-Spider** [comment]
Wiki page completed! https://github.com/Nyphet/soul-fire-d/wiki/Data-Driven-Fires
