### ISSUE TITLE
Appropriate incompatible enchantments

### ISSUE THREAD

**Issue by polykatt** [Crystal-Nest/soul-fire-d#43]
### I have confirmed no other issue asks for this

- [X] I have searched for existing issues

### Other mod

Simple Enchantments by InfernalEclipse

### Current behavior

The Simple Enchantments mod adds "hail" for bows. The enchantment is incompatible with flame (as it freezes the target) but not so with soul flame.

### Desired behavior

Have soul flame enchantment be incompatible with hail

**Comment by Crystal-Spider** [comment]
I'd say to ask the other mod author to add this feature.

Soul Flame enchantment extends the base Flame enchantment and uses the same compatibility check with extra narrowing conditions.  
I guess, on their side, compatibility with their Hail enchantment is computed by checking if the other enchantment is Flame rather than checking the Java class, so Soul Flame doesn't get detected properly by them.

Furthermore, their code is not open source, so it's harder for me to add compatibility than it is for them.

**Comment by Crystal-Spider** [comment]
They replied to your issue [here](https://legacy.curseforge.com/minecraft/mc-mods/simple-enchantments/issues/1), I'm closing this.
