### ISSUE TITLE
How to configure enchantments

### ISSUE THREAD

**Issue by DeltaV-1** [Crystal-Nest/soul-fire-d#49]
### I have confirmed no other issue asks the same question

- [X] I have searched for existing issues

### Question

I want to know how I'm supposed to disable/enable the Soul Flame/Fire Aspect enchantments. I want it so that all this mod does is just make it so that the burn overlay is blue fire instead of orange. I want to keep the vanilla damage the same and I want the enchantments removed, but I don't know how I'm supposed to do this.

**Comment by Crystal-Spider** [comment]
Fire damage cannot be changed, but it is consistent with Vanilla as Soul Fire deals double damage.

About enchantments, it depends on the Minecraft version you're using.

Before 1.21:  
There is a configuration option to disable both enchantments.

Since 1.21:  
To remove enchantments, you need to create a data pack that removes them.  
You'll need to add a new `enchantable` tag that contains no items, and then override Soul Fire'd enchantments by copy-pasting the files and changing the `supported_items` property to your new tag.  
You'll also want to override the `in_enchanting_table`, `tradeable`, and `treasure` tags to restore Vanilla ones (you can do so by copy-pasting those files from Vanilla and add them to your data pack, but adding `"replace": true` to each).
